name = "xpath://input[@name='name']"
phone = "css:input[name='phone']"
email = "name:email"
country = "xpath://select[@name='country']"
city = "xpath://input[@name='city']"
username = "xpath://div[@id='load_box']//input[@name='username']"
password = "xpath://div[@id='load_box']//input[@name='password']"
submit_btn = "xpath://div[@id='load_box']//input[@value='Submit']"
